def USE_K8S = false

pipeline {

    agent { label 'ec2-agent' }

    parameters {
        string(name: 'REPLICAS', defaultValue: '3', description: 'Number of replicas')
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag')
    }

    environment {
        KUBECONFIG = "/home/ubuntu/.kube/config"
        NAMESPACE  = "devops"
        RELEASE    = "python-app"
        CHART      = "./Helm"
    }

    stages {

        // ===============================
        // Detect Kubernetes Dynamic Agent
        // ===============================
        stage('Detect Kubernetes Availability') {
            steps {
                script {
                    try {
                        timeout(time: 120, unit: 'SECONDS') {
                            node('tools-agent') {
                                sh "echo 'K8S agent available'"
                            }
                        }
                        USE_K8S = true
                    } catch (err) {
                        USE_K8S = false
                    }
                }
            }
        }

        // ===============================
        // Helm Upgrade
        // ===============================
        stage('Helm Upgrade') {
            steps {
                script {
                    if (USE_K8S) {
                        node('tools-agent') {
                            checkout scm
                            container('tools') {
                                sh """
                                helm upgrade ${RELEASE} ${CHART} \
                                  --namespace ${NAMESPACE} \
                                  --set replicaCount=${REPLICAS} \
                                  --set image.tag=${IMAGE_TAG}
                                """
                            }
                        }
                    } else {
                        sh """
                        helm upgrade ${RELEASE} ${CHART} \
                          --namespace ${NAMESPACE} \
                          --set replicaCount=${REPLICAS} \
                          --set image.tag=${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        // ===============================
        // Verify
        // ===============================
        stage('Verify') {
            steps {
                sh "kubectl -n ${NAMESPACE} get deploy"
            }
        }
    }
}
